name: RSpec Tests

on:
  push:
    branches:
      - develop

jobs:
  rspec:
    strategy:
      matrix:
        ruby: ['3.2.1', '3.2.0']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run RSpec tests
        run: rspec
